### PR TITLE
#155738450 configure circleci and add badge

### PR DESCRIPTION
**Pull request by damafeez**
**What does this PR do?**
This PR configures and sets up circleci(Finishes [story](https://www.pivotaltracker.com/n/projects/2155295/stories/155738450))

**Description of Task to be completed?**
- add circleci config.yml
- add cicleci badge to readme.md

**How should this PR be manually tested**
- merge this PR and observe CircleCI build badge

**Any background context you want to provide?**
N/A

**What are the relevant pivotal tracker stories?**
#155738450

**Screenshots (if appropriate)**
image

**Questions:**
None

### CODE REVIEW

**Comment by phemonick** [comment]
Nice work @damafeez, Can you add a screenshot of the badge

**Comment by damafeez** [comment]
> Nice work @damafeez, Can you add a screenshot of the badge

Ok, I'll see to that

**Comment by damafeez** [comment]
> Nice work @damafeez, Can you add a screenshot of the badge

I fixed this!

**Comment by phemonick** [comment]
Nice, LGTM

**Pull request merged**
